version: '3.4'

services:
  websocketmessenger.api:
    image: ${DOCKER_REGISTRY-}websocketmessengerapi
    build:
      context: .
      dockerfile: WebSocketMessenger.API/Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}; 
    depends_on: 
        - db
    networks:
        - backend

  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks: 
        - backend
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres_data:
networks:
  backend:
